"""“UpdateManyToMany”

Revision ID: 0b0452ed824e
Revises: 77ee7d0d95d3
Create Date: 2024-12-30 12:16:00.081801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b0452ed824e'
down_revision: Union[str, None] = '77ee7d0d95d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_garage', sa.Column('car_id', sa.Integer(), nullable=False))
    op.drop_constraint('car_garage_garage_id_fkey', 'car_garage', type_='foreignkey')
    op.create_foreign_key(None, 'car_garage', 'cars', ['car_id'], ['id'])
    op.create_foreign_key(None, 'car_garage', 'cars', ['garage_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car_garage', type_='foreignkey')
    op.drop_constraint(None, 'car_garage', type_='foreignkey')
    op.create_foreign_key('car_garage_garage_id_fkey', 'car_garage', 'garages', ['garage_id'], ['id'])
    op.drop_column('car_garage', 'car_id')
    # ### end Alembic commands ###
