"""“FixManyToMany”

Revision ID: 0b2e07ce2af5
Revises: 81b1a1fb2b3f
Create Date: 2024-12-30 13:20:41.013292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b2e07ce2af5'
down_revision: Union[str, None] = '81b1a1fb2b3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('car_garage_garage_id_fkey', 'car_garage', type_='foreignkey')
    op.create_foreign_key(None, 'car_garage', 'garages', ['garage_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car_garage', type_='foreignkey')
    op.create_foreign_key('car_garage_garage_id_fkey', 'car_garage', 'cars', ['garage_id'], ['id'])
    # ### end Alembic commands ###
