"""“AddManyToMany”

Revision ID: 77ee7d0d95d3
Revises: 5d8b180040fe
Create Date: 2024-12-29 20:56:25.059467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ee7d0d95d3'
down_revision: Union[str, None] = '5d8b180040fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('car_garage_car_id_fkey', 'car_garage', type_='foreignkey')
    op.drop_column('car_garage', 'car_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_garage', sa.Column('car_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('car_garage_car_id_fkey', 'car_garage', 'cars', ['car_id'], ['id'])
    # ### end Alembic commands ###
