"""“UpdateRelationships”

Revision ID: 81b1a1fb2b3f
Revises: 0b0452ed824e
Create Date: 2024-12-30 13:14:11.847363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81b1a1fb2b3f'
down_revision: Union[str, None] = '0b0452ed824e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
